import{a as v,S as L,i as c}from"./assets/vendor-frHSA4Lh.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const S="50282426-bcbed3422443d463b1ec5299f",B="https://pixabay.com/api/",C=15;async function P(t,r){const s={key:S,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:C};return(await v.get(B,{params:s})).data}const p=document.querySelector(".gallery"),m=document.querySelector(".loader"),f=document.querySelector(".load-more"),M=new L(".gallery a",{captionsData:"alt",captionDelay:250});function $(t){const r=t.map(s=>{const{webformatURL:i,largeImageURL:e,tags:o,likes:n,views:h,comments:b,downloads:w}=s;return`
      <li class="gallery-item">
        <a href="${e}"><img class="gallery-image" src="${i}" alt="${o}"/></a>
        <div class="stats">
          <p><span>Likes</span><span>${n}</span></p>
          <p><span>Views</span><span>${h}</span></p>
          <p><span>Comments</span><span>${b}</span></p>
          <p><span>Downloads</span><span>${w}</span></p>
        </div>
      </li>
        `}).join("");p.insertAdjacentHTML("beforeend",r),M.refresh()}function q(){p.innerHTML=""}function E(){m.style.visibility="visible"}function R(){m.style.visibility="hidden"}function A(){f.style.visibility="visible"}function y(){f.style.visibility="hidden"}const I=document.querySelector(".form"),O=document.querySelector(".load-more");let l,a=1;const u=15;let d="";I.addEventListener("submit",async t=>{t.preventDefault(),y(),q(),l=t.target.elements["search-text"].value.trim(),l&&await g(l)});O.addEventListener("click",async()=>{y(),await g(l),x()});async function g(t){if(t){E(),d!==t&&(a=1,d=t);try{const r=await P(t,a,u),s=r.hits;s&&s.length>0?($(s),a>=Math.ceil(r.totalHits/u)?c.show({title:"ℹ️",message:"We're sorry, but you've reached the end of search results.",messageColor:"white",titleColor:"white",backgroundColor:"#4CAF50",position:"topRight"}):A()):c.show({title:"❌",message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",titleColor:"white",backgroundColor:"#ef4040",position:"topRight"}),a++}catch(r){console.error(r)}finally{R()}}}function x(){const t=document.querySelector(".gallery-item");t&&setTimeout(()=>{scrollBy({top:t.getBoundingClientRect().height*2,left:0,behavior:"smooth"})},200)}
//# sourceMappingURL=index.js.map
